name: windows wheels

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        python: ['3.11']
        toxenv: [test]
        toxargs: [-v]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - run: python -m pip install .

    - if: always()
      run: python -m pip list

    - if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ufunc.c
        path: erfa/ufunc.c