name: windows wheels

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: w/ numpy ${{ matrix.numpy }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: ['3.11']
        numpy: [stable, dev]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - run: |
        python -m pip install -U pip
        python -m pip install setuptools setuptools_scm jinja2
    
    - if: matrix.numpy == 'stable'
      run:
        python -m pip install 'numpy<2'

    - if: matrix.numpy == 'dev'
      run: |
        python -m pip install numpy --only-binary ':all:' \
           --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple

    - run: python -m pip install . --no-build-isolation

    - if: always()
      run: python -m pip list

    - if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ufunc_numpy_${{ matrix.numpy }}.c
        path: erfa/ufunc.c